server:
  port: 7001

spring:
  application:
    name: api-service
  elasticsearch:
    rest:
      uris: localhost:9200
  data:
    mongodb:
      database: picstories
      uri: mongodb://localhost/picstories